DEFINITIONS EXPLICIT TAGS ::=
BEGIN

a  OCTET STRING ::= "Hallo"
b1  BOOLEAN ::= FALSE
b2  BOOLEAN ::= TRUE
d1 INTEGER ::= 1234
d2 INTEGER ::= -99
f  OBJECT IDENTIFIER ::= {1 2 3}
n NULL ::= NULL

END


DEFINITIONS EXPLICIT TAGS ::=
BEGIN

a  OCTET STRING ::= "Hallo"
b1  BOOLEAN ::= FALSE
b2  BOOLEAN ::= TRUE
d1 INTEGER ::= 1234
d2 INTEGER ::= -99
f  OBJECT IDENTIFIER ::= { 1 2 3 }
n NULL ::= NULL

END
