DEFINITIONS EXPLICIT TAGS ::=
BEGIN

a  OCTET STRING ::= "Hallo"
b  BOOLEAN ::= FALSE
d1 INTEGER ::= 1234
d2 INTEGER ::= -99
f  OBJECT IDENTIFIER ::= {1 2 3}

END


DEFINITIONS EXPLICIT TAGS ::=
BEGIN

a  OCTET STRING ::= "Hallo"
b  BOOLEAN ::= FALSE
d1 INTEGER ::= 1234
d2 INTEGER ::= -99
f  OBJECT IDENTIFIER ::= {1 2 3}

END
